#Database
RDSSubnetGroup:
  Type: AWS::CloudFormation::Stack
  Properties:
    TemplateURL: https://cf-templates-g4ool1dn68hz-us-east-1.s3.amazonaws.com/components/DBSubnetGroup.yaml
    Parameters:
      DBSubnetGroupDescription: Private Database Subnet Group
      SubnetIds: !Join
        - ","
        - - !GetAtt VPC.Outputs.PrivateSubnet1ID
          - !GetAtt VPC.Outputs.PrivateSubnet2ID
          - !GetAtt VPC.Outputs.PrivateSubnet3ID
SecretRDS:
  Type: "AWS::SecretsManager::Secret"
  Properties:
    Description: "This is a Secrets Manager secret for an RDS DB instance"
    GenerateSecretString:
      ExcludeNumbers: false
      ExcludePunctuation: true
      ExcludeUppercase: false
      GenerateStringKey: "password"
      IncludeSpace: false
      RequireEachIncludedType: true
      PasswordLength: 16
      SecretStringTemplate: '{"username": "admin"}'
SecretRDSInstanceAttachment:
  Type: "AWS::SecretsManager::SecretTargetAttachment"
  Properties:
    SecretId: !Ref SecretRDS
    TargetId: !GetAtt RDSCluster.Outputs.ClusterIdentifier
    TargetType: AWS::RDS::DBCluster
RDSCluster:
  Type: AWS::CloudFormation::Stack
  Properties:
    TemplateURL: https://cf-templates-g4ool1dn68hz-us-east-1.s3.amazonaws.com/components/RDSCluster.yaml
    Parameters:
      DBClusterIdentifier: aurora-mysql-cluster
      DBSubnetGroupName: !GetAtt RDSSubnetGroup.Outputs.DBSubnetGroupName
      EnableIAMDatabaseAuthentication: false
      Engine: aurora-mysql
      EngineMode: provisioned
      MasterUsername: !Join
        - ""
        - - "{{resolve:secretsmanager:"
          - !Ref SecretRDS
          - ":SecretString:username}}"
      MasterUserPassword: !Join
        - ""
        - - "{{resolve:secretsmanager:"
          - !Ref SecretRDS
          - ":SecretString:password}}"
      VpcSecurityGroupIds: !Join
        - ","
        - - !GetAtt VPC.Outputs.SecurityGroupDB
RDSWritter:
  Type: AWS::CloudFormation::Stack
  Properties:
    TemplateURL: https://cf-templates-g4ool1dn68hz-us-east-1.s3.amazonaws.com/components/RDSDBInstance.yaml
    Parameters:
      DBClusterIdentifier: !GetAtt RDSCluster.Outputs.ClusterIdentifier
      DBInstanceIdentifier: aurora-mysql-instance1
      DBInstanceClass: db.t2.small
      DBSubnetGroupName: !GetAtt RDSSubnetGroup.Outputs.DBSubnetGroupName
      Engine: aurora-mysql
      MonitoringInterval: 0
      PubliclyAccessible: false
