AWSTemplateFormatVersion: "2010-09-09"
Resources:
  # Networking
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cf-templates-g4ool1dn68hz-us-east-1.s3.amazonaws.com/components/VPC.yaml
  EC2Instance1:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cf-templates-g4ool1dn68hz-us-east-1.s3.amazonaws.com/components/EC2.yaml
      Parameters:
        SubnetId: !GetAtt VPC.Outputs.PublicSubnet1ID
        NameOfService: puppet
        SecurityGroups: !Join
          - ","
          - - !GetAtt VPC.Outputs.SecurityGroupEC2
  ALB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cf-templates-g4ool1dn68hz-us-east-1.s3.amazonaws.com/components/LoadBalancer.yaml
      Parameters:
        IpAddressType: ipv4
        Scheme: internet-facing
        SecurityGroups: !Join
          - ","
          - - !GetAtt VPC.Outputs.SecurityGroupEC2
        Subnets: !Join
          - ","
          - - !GetAtt VPC.Outputs.PublicSubnet1ID
            - !GetAtt VPC.Outputs.PublicSubnet2ID
            - !GetAtt VPC.Outputs.PublicSubnet3ID
        Type: application
  LoadBalancerListener:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cf-templates-g4ool1dn68hz-us-east-1.s3.amazonaws.com/components/LoadBalancerListener.yaml
      Parameters:
        LoadBalancerArn: !GetAtt ALB.Outputs.Arn
        Port: 80
        Protocol: HTTP
        TargetGroupArn: !GetAtt TargetGroup.Outputs.TargetGroupArn
  TargetGroup:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cf-templates-g4ool1dn68hz-us-east-1.s3.amazonaws.com/components/TargetGroup.yaml
      Parameters:
        HealthCheckEnabled: true
        HealthCheckIntervalSeconds: 30
        HealthCheckPath: /chat
        HealthCheckPort: traffic-port
        HealthCheckProtocol: HTTP
        HealthCheckTimeoutSeconds: 5
        HealthyThresholdCount: 5
        MatcherHttpCode: 200
        Port: 80
        Protocol: HTTP
        TargetType: instance
        UnhealthyThresholdCount: 2
        VpcId: !GetAtt VPC.Outputs.VPCID
        Target1Id: !GetAtt EC2Instance1.Outputs.InstanceId
        Target1Port: 80
