Parameters:
  LoadBalancerArn:
    Description: The HealthCheckProtocol TCP/UDP etc.
    Type: String
  Port:
    Description: The HealthCheckProtocol TCP/UDP etc.
    Type: String
  Protocol:
    Description: The HealthCheckProtocol TCP/UDP etc.
    Type: String
    Default: HTTP
  TargetGroupArn:
    Description: The TargetGroupARN
    Type: String
Resources:
  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroupArn
      LoadBalancerArn: !Ref LoadBalancerArn
      Port: !Ref Port
      Protocol: !Ref Protocol
