Parameters:
  NameOfService:
    Description: stack description
    Type: String
    Default: EC2 instance
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access into the server
    Type: String
    Default: aws-eb
  UserData:
    Description: EC2 instance bootstrap script
    Type: String
    Default: "#!/bin/bash"
  SubnetId:
    Description: SubnetId
    Type: String
    Default: ""
Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-003f19e0e687de1cd
Resources:
  # Create an elastic IP so that the ip address doesn't change.
  IPAddress:
    Type: AWS::EC2::EIP
    # Add the Elastic IP to the EC2 instance.
  IPAssoc:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref "EC2Instance"
      EIP: !Ref "IPAddress"
    # Create the EC2 instance.
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId:
        Fn::FindInMap:
          - RegionMap
          - !Ref AWS::Region
          - AMI
      SecurityGroupIds:
        - !ImportValue SG-SecurityGroup1
      Tags:
        - Key: Name
          Value: !Ref NameOfService
      KeyName: !Ref KeyName
      SubnetId: !Ref SubnetId
      "Fn::Transform":
        Name: "AWS::Include"
        Parameters:
          Location: !Ref UserData
Outputs:
  Website:
    Description: The Public DNS for the EC2 Instance
    Value: !Sub "http://${EC2Instance.PublicDnsName}"
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref "EC2Instance"
  InstanceIPAddress:
    Description: IP address of the newly created EC2 instance
    Value: !Ref "IPAddress"
